server:
  port: 8080
spring:
  application:
    name: msc-consumer-depart


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: msc-consumer-depart-8080