server:
  port: 8081

eureka:
  client:
    service-url:
      # 指定要连接的Eureka服务中心地址
      defaultZone: http://localhost:8100/eureka,http://localhost:8200/eureka,http://localhost:8300/eureka
  # 该服务在注册中心中的名称
  instance:
    instance-id: msc-provider-depart-8081
#    # 配置客户端多长时间不向服务端发送心跳，就可以让服务端认为当前客户端已经挂了
#    lease-expiration-duration-in-seconds: 3
#    # 配置客户端向服务端发送的心跳间隔
#    lease-renewal-interval-in-seconds: 1
spring:
  application:
    # 该微服务名称
    name: msc-provider-depart
  # 使用jpa，是否自动创建表
  jpa:
    generate-ddl: true

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
# 配置 actuator，添加该应用详细信息
info:
  auth: Eleven
  app.name: ${spring.application.name}
  company.name: www.eleven.cn
  company.addr: hangzhou china

# 配置日志
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    # 指定spring.jpa.show-sql为true时，是否显示动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 指定spring.jpa.show-sql为true时，是否显示查询语句的查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.provider: debug