server:
  port: 8081

# 设置Spring-Data-JPA
spring:
  jpa:
    # 指定在Spring容器启动时是否自动建表
    generate-ddl: true
    # 指定在控制台是否显示SQL语句
    show-sql: true
    # 指定应用启动时是否重新建表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

# 配置日志
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    # 指定spring.jpa.show-sql为true时，是否显示动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 指定spring.jpa.show-sql为true时，是否显示查询语句的查询结果
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    com.abc.provider: debug
