server:
  port: 8000

eureka:
  instance:
    # Eureka主机名称
    hostname: localhost
  client:
    # 是否向注册中心注册，不需要，自己就是服务中心
    register-with-eureka: false
    # 指定此客户端是否能获取Eureka的注册信息
    fetch-registry: false
    # 暴露服务中心地址，客户端通过这个地址进行访问
    service-url:
      # 使用${}可以获取当前配置文件中的变量参数，此处等价于：http://localhost:8000/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

#  server:
#    # 配置自我保护阈值，默认0.85
#    renewal-percent-threshold: 0.85
#    # 配置是否开启自我保护模式，默认是开启的
#    enable-self-preservation: true
#    # 配置服务器剔除不可用服务的时间窗，默认是0
#    eviction-interval-timer-in-ms: 0