server:
  port: 8000

eureka:
  instance:
    # Eureka主机名称
    hostname: localhost
  client:
    # 是否向注册中心注册，不需要，自己就是服务中心
    register-with-eureka: false
    # 指定此客户端是否能获取Eureka的注册信息
    fetch-registry: false
    # 暴露服务中心地址，客户端通过这个地址进行访问
    service-url:
      # 使用${}可以获取当前配置文件中的变量参数，此处等价于：http://localhost:8000/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka